### ISSUE TITLE
Does not work on 1.20.1

### ISSUE THREAD

**Issue by CorneliusCornbread** [2008Choco/DragonEggDrop#41]
attempting to use this on a 1.20.1 paper server results in the following output
```
[02:19:04 ERROR]: Error occurred while enabling DragonEggDrop v1.1.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/IChatBaseComponent
	at com.ninjaguild.dragoneggdrop.DragonEggDrop.onEnable(DragonEggDrop.java:41) ~[DragonEggDrop-94945 (PP).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-164]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-164]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-164]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[02:19:04 INFO]: [DragonEggDrop] Disabling DragonEggDrop v1.1.6
```

**Comment by 2008Choco** [comment]
The DragonEggDrop version you are using was abandoned back in Minecraft 1.10. This error isn't actually from this plugin. This plugin is a fork of the plugin you are using and can be found and downloaded [here](https://www.spigotmc.org/resources/dragoneggdrop-revival.35570/). It has more features and configuration options but I cannot guarantee that it works on the latest version either given that I've mostly dropped support for this plugin.

You can try the latest version of my fork, but I cannot guarantee anything beyond that.
